# Dockerfile for a node container, to be included as part of a docker-compose
# file. This does not start the app on it's own, but sets up the environment,
# prepping to be run in the compose file.
FROM node:9.3.0-alpine

# Install forever
RUN npm install forever -g

# Create a source directory
RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server

RUN mkdir data && touch data/mta_status.xml && touch data/mta_status.json

# Install dependencies
COPY package.json .

RUN npm install

# Copy in the repo.
COPY . .

EXPOSE 8100

# Run app from docker-compose.xml
CMD ["forever", "server.js"]